services:
  db_vitrine:
    image: postgres:16
    container_name: db_vitrine
    restart: always
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5439:5432"
    networks:
      - app-network_vitrine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app_user -d app_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  back_vitrine:
    build: 
      context: ./back
      args:
        BUILDKIT_INLINE_CACHE: 1
    container_name: back_vitrine
    ports:
      - "8009:8000"
    env_file:
      - ./back/.env
    networks:
      - app-network_vitrine
    depends_on:
      db_vitrine:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://10.37.44.204:8000/api/health || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s

  front_vitrine:
    build: ./front
    container_name: front_vitrine
    ports:
      - "5179:5173"
    volumes:
      - ./front:/app
      - front-node-modules:/app/node_modules
    networks:
      - app-network_vitrine
    depends_on:
      - back_vitrine
    environment:
      - CHOKIDAR_USEPOLLING=true

networks:
  app-network_vitrine:

volumes:
  db-data:
  front-node-modules:

